### ISSUE TITLE
EN standard level check - code tidying and testing

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#133]
An initial attempt at the EN standard level background and buddy check has been made (#131, #132). The code is complex and requires some tidying (separating code into functions etc.) Although the code appears to be doing something sensible, all the parts of the code need to have tests implemented to ensure that it is working correctly.

**Comment by BillMills** [comment]
Hi Simon - happy to start having a look at this this weekend, thanks for pulling it together! I like where you're going with both the persistence of test results on the module variables `*.uid` and `*.qc` to avoid rerunning things, and on looking across the full set of profiles to find buddies. On first inspection, I have a couple of questions:

 - It seems like the results for a given test are persisted only for the current uid, and overwritten on the next, which I think means that in almost all cases, `stdLevelData` will not find a uid match and therefore will rerun the test, even though it's been run previously. I sketched out an alternative solution to this in my draft of the track check, where a global key / value store is kept for *every* profile and its qc result; so instead of having `*.uid` and `*.qc`, we could have a module variable that's a dictionary like 
```
{
  "uid_0": qc_0,
  "uid_1": qc_1,... 
}
```

 - I see you've made the profile list a global variable in #131 and examine it in the buddy check to look for buddies, without the need to a-priori sort related profiles into the same file before parallelization - I love it, that's really slick! My concern here is related to my last point; I agree your method should work, but even if we do persists a list of results for every profile, without pre-sorting it seems like those results will be in a different thread and thus invisible to their buddy, resulting in re-running tests a lot.

Does it sound like I've misunderstood something? Let me know if so. Worst case scenario is still not a showstopper - we can throw extra computing power at this to rerun some tests, but it would be nice to avoid the extra expense if possible. Let me know and I'll start tidying.

**Comment by s-good** [comment]
Hi @BillMills  - thanks for looking at this! Yes, you're right on both points. As I only set it up to save the QC result from the last examined profile it is currently necessary to rerun QC for a buddy profile if it exists (this won't always happen). So it would be better to store QC results for all profiles that have been examined (as long as we don't start to eat up too much memory I guess) and then also it would be most efficient to pre-sort the profiles so that profiles that might buddy with each other are examined in the same process. I think that by having the global list it should make it so that the QC results are identical no matter how the profiles are divided up into different files, but the better the profiles are divided up the more efficient it will be, so we should get the best of both worlds.

**Comment by BillMills** [comment]
Okay great, we agree on all of this - I'll start with tidying things as is and moving to a complete list of persisted qc decisions so we can close out here, and upgrade sorting next.

**Comment by BillMills** [comment]
Done modulo #136.
