### ISSUE TITLE
woa_normbias bug

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#173]
Profile 542348 throws an error in one of the CoTeDe tests:

```
Traceback (most recent call last):
  File "AutoQC.py", line 105, in <module>
    parallel_result = processFile.parallel(filenames)
  File "/AutoQC/util/main.py", line 117, in easy_parallize
    result = pool.map(f, sequence) # for i in sequence: result[i] = f(i)
  File "/opt/conda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/conda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'woa_normbias'
```
Profile content:

```
C32306542348996900447199412 433278044222454426806150 21101022501021311 9NAVOCE 9
42421511110022911022541101271110129977020161270110000331999101100001105003312660
0110500110800331272001108002204700220270022047002205900331265002205900
```

**Comment by s-good** [comment]
I think this has occurred because the latest version of the cotede_test.py routine preferentially uses the CoTeDe config files and runs only a single test each time. It was originally set up to run all the tests defined in a config file at once and save the results of all. In this case it thinks it has done the latter and that the woa_normbias QC test has been run but it has actually done the former. NB I haven't been able to reproduce the problem yet (I think I need to update my versions of CoTeDe, wodpy and AutoQC...) but I am pretty sure this is the problem. I will put in a pull request that I expect to fix it.

**Comment by s-good** [comment]
#175 was intended to fix this, but I'm now sceptical. The section of code that was meant to read the configuration from CoTeDe was not working because of a missing import. As the missing import was in a try, except statement that was being quietly dealt with by the code defaulting to the versions in the AutoQC repository. This means, though, that my theory of why this key error is occurring can't be correct. The profile itself looks OK so this is a bit of a mystery. It would be interesting to know if my changes have inadvertently solved the problem, otherwise I will continue to look into it.

**Comment by s-good** [comment]
I think I have tracked this down to a bug in CoTeDe - see https://github.com/castelao/CoTeDe/pull/30. Once that pull request is merged I will check to see if the error has gone.

**Comment by s-good** [comment]
@castelao suggests using the CoTeDe dev branch as this contains the fix for this issue.

**Comment by s-good** [comment]
The CoTeDe dev branch has been merged with the master so the problem should go away if we upgrade to the latest version. The warning messages about configuration being deprecated look like they will still occur though.

**Comment by BillMills** [comment]
Looks good - latest docker image reflecting this update is live on dockerhub.
