### ISSUE TITLE
are we sure about this test?

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#252]
https://github.com/IQuOD/AutoQC/blob/master/tests/EN_background_check_validation.py#L36-L49 is a unit test on the background check's lat/long binner, and is currently the only test not passing in my environment for out py2->py3 port of #248, and I'm suspicious of what it's asserting in the latitude test. It appears to be insisting that the test latitude provided should wrap around to the highest bin in the latitude grid points since it underflows the lowest bin, even though it's clearly closer to the lowest bin. 

Not sure if this was intentional or not - @s-good is the unit test as written the behaviour we want, or should we actually be returning the index of the closest grid point?

**Comment by s-good** [comment]
The test is wrong - the answer should be ilat is zero. The difference in behaviour between python 2 and 3 is due to python3 defaulting to doing sums as floats. The test defines all the numbers as integers so python2 does integer division and gets the wrong answer. This is compounded by an error in the code, which is incorrectly doing a modulus operation for the latitude grid, which means that a point in the far south can get assigned to a grid point in the far north. 

Fortunately neither situation should be a significant problem in reality as the lons and lats are floats and we should never get any data beyond the southernmost point in the grid. The use of modulus for latitude might mean that any profiles at 90 degrees north cause a problem, though.

**Comment by BillMills** [comment]
That's what I thought; I'll roll up fixes to the function and unit test in #248, unless we need them sooner.

**Comment by BillMills** [comment]
Resolved in https://github.com/IQuOD/AutoQC/pull/248/commits/c49ef92a2f7e05e7f331f147160a908d5cfb3e3a; I replace the modulo with a function to map latitudes onto [-90, 90], and re-write the corresponding unit test not only to pass but to be slightly more physical.
