### ISSUE TITLE
Code up WOD gradient check

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#27]
As part of an intercomparison of 'spike tests' (#21) code up the excessive gradient test described at http://data.nodc.noaa.gov/woa/WOD/DOC/wodreadme.pdf on page 47. The program file should be called WOD_gradient_check.py and be put into the qctests directory. It should follow the structure shown in EN_range_check.py.

**Comment by BillMills** [comment]
Similar question to my first post in #25 - this test is applied to many different parameters; does it make sense to test them separately, or combine them somehow (and if so, how? AND or OR?)

Also, looking ahead - how shall we deal with missing values when evaluating these tests? Let the dataset stand since the specific test couldn't identify a problem with it, or fail it for being incomplete?

**Comment by s-good** [comment]
As with #25, lets just work on the temperature tests at the moment and ignore the others. If there are missing data they should assume to stand rather than failing it, I think.
