### ISSUE TITLE
Code up EN track check

### ISSUE THREAD

**Issue by s-good** [IQuOD/AutoQC#54]
Code up the constant value check described at http://www.metoffice.gov.uk/hadobs/en3/OQCpaper.pdf page 7. The program file should be called EN_track_check.py and be put into the qctests directory. It should follow the structure shown in EN_range_check.py.

This is quite a challenging check to code up as the check needs to use information about other profiles rather than just the profile itself. Therefore the whole list of profiles will need to be passed in as an additional argument.

**Comment by BillMills** [comment]
I'll have to look a bit closer, but instead of passing as an argument, we could load the list of profile headers (just the headers, not the level data) as part of the global datastore being introduced in #84 for `WOD_range`; that way, we avoid having to add special cases or extra kwargs to the main routine to support individual tests. Not necessarily better - just an alternative that I think might help avoid blowing up the complexity of the main routine in future.

**Comment by BillMills** [comment]
resolved in #93.
