### ISSUE TITLE
correct temperature conversions between t48 and t68

### ISSUE THREAD

**Issue by BillMills** [IQuOD/AutoQC#90]
There's a note in `obs_utils.t48tot68()` questioning whether the conversion implemented is correct; the same equation is reported [here](http://cfconventions.org/Data/cf-standard-names/27/build/cf-standard-name-table.html) and [here](http://www.teos-10.org/pubs/gsw/pdf/t90_from_t48.pdf); are there other conflicting references?

**Comment by s-good** [comment]
The problem in the equation in http://cfconventions.org/Data/cf-standard-names/27/build/cf-standard-name-table.html is that the final set of brackets says (100 - t - 48) rather than (100 - t48), which makes more sense. The second reference clears up an ambiguity so I will remove the warning messages from obs_utils.748to768(). Thanks for finding that @BillMills !

**Comment by s-good** [comment]
The change has been committed to master.
